language: java
jdk:
  - oraclejdk7
env:
  - PLAY_VERSION=2.2.1
before_script:
  - wget http://downloads.typesafe.com/play/2.2.1/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script:
  - play-${PLAY_VERSION}/play test
notifications:
  email: false